{% set name = "injective-py" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/InjectiveLabs/sdk-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b25a404a0bee348c6f3b63526187a4520fe336a922b7572871353bfb56af3190
  patches:
    - fix-protobuf-test-fail.patch
    - clean-lib-dependencies.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv
  number: 0

requirements:
  host:
    - aiohttp >=3.9.2
    - python >=3.9.0
    - pip
    - poetry
  run:
    - bech32
    - bip32
    - ecdsa
    - eip712
    - grpcio
    - mnemonic
    - python >=3.9.0
    - requests
    - safe-pysha3
    - web3 >=6

test:
  imports:
    - pyinjective
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-grpc
    - requests-mock
  commands:
    - pip check
    - pytest -v

about:
  home: https://github.com/InjectiveLabs/sdk-python
  summary: 'Injective Python SDK, with Exchange API client'
  license: Apache-2.0
  license_file:
    - LICENSE.md
    - NOTICE.md

extra:
  recipe-maintainers:
    - MementoRC
