{% set name = "injective-py" %}
{% set version = "1.11.1" %}

{% set python_min = "3.10" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/InjectiveLabs/sdk-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 62df0ec70cfffb98182052f6bcd25729d4c5c70c030aa659fc447934cde53835

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv
  number: 0

requirements:
  host:
    - aiohttp >=3.9.4
    - pip
    - poetry-core
    - python {{ python_min }}.*
  run:
    - bech32
    - bip32
    - ckzg
    - ecdsa
    - eip712
    - eth-abi
    - grpcio
    - grpcio-tools
    - hdwallets
    - mnemonic
    - protobuf <6.0.0,>=5.26.1
    - python >={{ python_min }}
    - requests
    - safe-pysha3
    - web3 >=7.0.0,<8.0.0

test:
  imports:
    - pyinjective
  source_files:
    - tests
    - examples
    - pyproject.toml
  requires:
    - pip
    - poetry
    - pytest
    - pytest-asyncio
    - pytest-grpc
    - python {{ python_min }}.*
    - requests-mock
  commands:
    - pip check
    # Documented (incorrectly) examples do not work
    # - poetry run python examples/exchange_client/spot_exchange_rpc/8_StreamOrderbookUpdate.py
    # - poetry run python examples/chain_client/3_MessageBroadcaster.py

    # Some tests are failing
    - poetry run pytest || true

about:
  home: https://github.com/InjectiveLabs/sdk-python
  summary: 'Injective Python SDK, with Exchange API client'
  license: Apache-2.0
  license_file:
    - LICENSE.md
    - NOTICE.md

extra:
  recipe-maintainers:
    - MementoRC
