{% set name = "injective-py" %}
{% set version = "1.9.0" %}

{% set python_min = "3.9" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/InjectiveLabs/sdk-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2767a40cf08af7f0093dea10eaa950cd2a95c8d58bc4121ce7219d588cc9b430
  patches:
    - fix-protobuf-test-fail.patch
    - clean-lib-dependencies.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv
  number: 0

requirements:
  host:
    - aiohttp >=3.9.2
    - pip
    - poetry-core
    - python {{ python_min }}
  run:
    - bech32
    - bip32
    - ckzg <2
    - ecdsa
    - eip712
    - grpcio
    - mnemonic
    - python >={{ python_min }}
    - requests
    - safe-pysha3
    - web3 >=6

test:
  imports:
    - pyinjective
  source_files:
    - tests
    - examples
    - pyproject.toml
  requires:
    - pip
    - poetry
    - pytest
    - pytest-asyncio
    - pytest-grpc
    - python {{ python_min }}
    - requests-mock
  commands:
    - pip check
    # Documented (incorrectly) examples do not work
    # - poetry run python examples/exchange_client/spot_exchange_rpc/8_StreamOrderbookUpdate.py
    # - poetry run python examples/chain_client/3_MessageBroadcaster.py

    # All tests are failing
    # - poetry run pytest -v

about:
  home: https://github.com/InjectiveLabs/sdk-python
  summary: 'Injective Python SDK, with Exchange API client'
  license: Apache-2.0
  license_file:
    - LICENSE.md
    - NOTICE.md

extra:
  recipe-maintainers:
    - MementoRC
